### ISSUE TITLE
Morning session: peer-to-peer code reviews (12-12-2022) PR #5

### ISSUE THREAD

**Issue by alex1779** [chibunduonyeje1/Portfolio-mobile#7]
# Introduction

This is a peer-to-peer code review exercise as part of the Microverse Full-stack engineering programme. 

Today we will review the last PR https://github.com/chibunduonyeje1/Portfolio-mobile/pull/5  and provide feedback on things he did right and areas we feel he might need to improve upon.

**Comment by SFarida** [comment]
Nicely done, I think this pull request is quiet pretty. I could not find an issue on the committed code.

**Comment by alex1779** [comment]
I don't see any errors in the code. Good work!

**Comment by anderCM** [comment]
## Add a new folder for all resources
I have found your code clean 😁. But, I think you should create a new folder called `assets` where you can storage all the resources in it's own folder following this example:
`project folder` > `assets` > `images` > `image.png`
`project folder` > `assets` > `audio` > `sound.mp3`
